### ISSUE TITLE
Is Pirateweather open source?

### ISSUE THREAD

**Issue by abetusk** [alexander0042/pirateweather#14]
From the website [pirateweather.net](https://pirateweather.net/), the by-line reads:

> A Free, Open, and Documented Forecast API

As of this writing, this project is, as far as I can tell, "closed source" (at least here in the US) since there is no indication about what license is that the project falls under. I don't see a LICENSE file for the project nor do I see license file headers in the source files. If I've missed these, my apologies.

"Open Source" has a generally accepted meaning of being able to use the digital artifacts for commercial purposes. The [OSI](https://opensource.org/osd) and Wikipedia's entry on [open-source licensing](https://en.wikipedia.org/wiki/Open-source_license) both articulate that commercial re-use is a (generally accepted) requirement of an "open source" license.

Was the intent to make this project libre/free/open source?

If so, could you indicate the license, either by providing a LICENSE file with the appropriate license or by putting a license preamble in each of the source files (preferably both).

If not, it might be good to clarify what the restrictions are to avoid confusion.

**Comment by alexander0042** [comment]
Hi, this is a really great point, so thank you for opening the issue! I'll be honest, when I first started out with this I was going to add a license, but when I started looking into the options, it just seemed like an overwhelming range of possibilities and I gave up on trying to decide. 

Since you seem to have more background here, I would love to hear your perspective. Basically, I want people to be able to use this code, including for commercial purposes. That gives me 3 options:
1. GNU AGPLv3. Since this applies explicitly to server use cases, there's an argument for it here. By my understanding, it would mean anyone using these scripts to serve weather data (or anything else I suppose) would have to open source their entire application.
2. Mozilla Public License. This would still let people use these scripts, and I believe require them to open-source any changes they make to them. This has some perks, since I'd love to see improvements released back, but without the limitations of requiring someone to open-source their entire application.
3. MIT. This was what I was originally leaning towards, since it's quick and to the point, just letting the code do it's thing. 

I think any of these would work, but I worry about the implications of selecting any of them, so very open to ideas here

**Comment by abetusk** [comment]
I can offer my opinion but know that I have my own biases which might be different from yours, so I urge you to look into it more so that you're choosing a license that meets with your intent.

I'll get into it more below, but as a quick reference, from my experience:

* AGPL(v3) is considered to be the "hard stance" libre/free/open source software position as anything that uses it (as a library, etc.) is required to also be libre/free
* MIT is considered to be "business friendly" because of its permissive structure.

So if your intent is to be libre/free and want to reduce the risk of some business using your work without giving back to the community, AGPL is probably a good license. If your intent is to be "business friendly" and want to encourage businesses to use your code, potentially at the risk of them making large portions of their "added value" code proprietary, then MIT is the better option.

In more detail:

1. [AGPL](https://en.wikipedia.org/wiki/Affero_General_Public_License)(v3) is a so-called "copyleft" (aka "viral") license, which means that people who use it (as a library, not an API?) or extend it will also need to publish their code under an AGPL. The AGPL's intent (as far as I can tell) is to update the GPL for the modern age and so specifically has wording about requiring people to publish code hidden behind a web-service, say (the FSF uses "tivo-ization" as their term for this, which is a sign of when this license was written). This means that even if you don't technically "redistribute" your code say, for example, as an API endpoint where the code lives on a server but is never technically run on a persons computer, you are still required to publish the source code.
2. I'm not too familiar with this license but from [Wikipedia](https://en.wikipedia.org/wiki/Mozilla_Public_License), it looks like this a "weak" copyleft license, so something like if you ship code with alterations, you have to provide it under the same license but if altering code on an API web service endpoint (say), you are not required to publish those changes.
3. [MIT](https://en.wikipedia.org/wiki/MIT_License) is the most "permissive" of these three, allowing for reuse with proprietary software so long as the original retains the MIT license.

For completeness, "[copyleft](https://en.wikipedia.org/wiki/Copyleft)" means the license is retained under derivative works and "[permissive](https://en.wikipedia.org/wiki/Permissive_software_license)" means derivative works need not be libre/free/open source software.

As a TLDR, here is a table copied over from the Wikipedia entry on "[Permissive software license](https://en.wikipedia.org/wiki/MIT_License)":

| | Public Domain | Permissive Licenses | Copyleft |
|---|---|---|---|
| Description | No rights retained | Use rights including relicensing | Use rights but forbids proprietization |
| Software | PD, CC0 | BSD, MIT, Apache | GPL, AGPL |
| Creative | PD, CC0 | CC-BY | CC-BY-SA |


From personal experience, individuals or businesses worried about "bad actor" usage of their code use AGPL as large-ish corporations tend to stay away from it to reduce their risk and individuals or businesses wanting to have their code be used in a commercial setting opt for the MIT license.

From what I gather, MIT is the [most popular license used](https://en.wikipedia.org/wiki/MIT_License).

Not at all a suggestion but as a point of reference of what I use, in case it's helpful, for the software that I create that might have business potential, I use AGPL to make sure that if other businesses use it, they're compelled to be "good actors". For other code or creative work that I just want people to use, I tend to put it under a CC0 (the equivalent of public domain) license. I've run into situations where I'm collaborating with someone and they specifically don't want to use AGPL code and want an MIT license (for the code created and any third party libraries used) because of its permissiveness.

**Comment by eseglem** [comment]
I love the idea of this project, and I found this issue because I was looking to help out and contribute. But the lack of a license certainly puts a damper on contributions. 

I feel it comes down to: How open do you want to be?

Personally, I put MIT on everything. But I just do small hobby projects and I don't care what others do with it. Another option would be Apache 2.0, which is what Home Assistant itself is licensed under. As well as your HA Integration. 

You would also need to comply with your own license, so AGPL would probably require you to release more code. Since I have not found any of the actual API implementation yet. 

One thing you may need to be careful of is where you got some of your code / parts from. You may have one file in here that is from another repo without a license. And if you got code from other places need to make sure you are complying with their licenses as well. 

I would be happy to help out. Just need a license decision first.

**Comment by alexander0042** [comment]
Thank you both for the explanations here, I really appreciate it. I'm new to all this, and have a habit of overthinking these types of decisions, so needed this push. 

Just pushed a change marking this as using the Apache license. While I really love the idea of copyleft, since these scripts are meant to be incorporated as a small piece of larger systems, I'm worried they might be too limiting here. Plus, I like that it aligns with the plug in!

@eseglem, I absolutely hear your point about the API implementation code, and it's something I'm hoping to release at some point, but isn't on here yet. It's a chaotic mess of Python, and since it is tied so heavily into AWS/ Lambda, I think it's utility is limited. My other worry is that I don't want Amazon to just copy that code and release it as a paid AWS, since that doesn't really jive with the spirit of the project, so I need to think about how I could avoid that.

**Comment by alexander0042** [comment]
Also, thank you for reminding me to check the other files in this repository! The only two things I can see are the parts of the developer portal, which is also Apache-2 <https://github.com/awslabs/aws-api-gateway-developer-portal>, and the wgrib2 Dockerfile, which was based on the NOAA install script so should be ok <https://www.ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/INSTALLING>
