### ISSUE TITLE
Precipitation Questions

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#24]
I know this has already been explained on the daily block but I was wondering when there's a mix of precipitation how it is determined which precipitationType is used for the hourly, minutely and currently blocks. I know DarkSky doesn't have any support for multiple precipitationTypes so I'm assuming that it chooses whichever one there's more of. So like if there's more rain than snow it chooses snow.

I know that some sites use the icon of the most prominent precipitation type and have the text say Rain and Snow or Rain/Freezing Rain as examples. So maybe something to consider when doing the text summaries.

**Comment by cloneofghosts** [comment]
I figured instead of creating a whole new issue I'd just add to this one. I had a couple more precipitation questions for you @alexander0042

1. On the currently block it seems like precipIntensity is only values that are a multiple of 0.36. Is there a reason for this or could it be a bug?
2. Are you able to fall back to the current hour precipitation intensity instead of defaulting to zero if there's no sub-hourly data? Might improve current conditions outside of the conus domain.

**Comment by alexander0042** [comment]
Great questions here, and I dug into them to make sure I got the answers correct:

1. I can't believe you spotted this- it's not really a bug, but more of an interesting processing quirk. When I process the ensemble data, which is where the precipitation intensities comes from, I drop all but the 0.1th digit (ex. 10.5245 = 10.5) from the model results ([see here](https://github.com/alexander0042/pirateweather/blob/4744667f178f4823519e8c66fd0ae865dcfa5c0f/scripts/gefs_combined-fargate.py#L197)). This saves a ton of space, and is a perfectly reasonable assumption, since 0.1 mm is about the limit for model accuracy anyway. Model data is 3-hourly accumulations, so this then gets divided by 3 (0.033) to get hourly data. When multiplied by the 10x snowfall factor, we get (roughly) the 0.36 factor that you're seeing, with the balance being due to the rounding and weighting between neighboring grid cells. This was a useful initial optimization, but I'm going to increase it to the 0.01th digit to add a bit more resolution here.
2. This one is a bug! Easy fix, so should be out (with a new version in the changelog) soon

**Comment by cloneofghosts** [comment]
For the first one precipitationIntensity on the currently block doesn't come from HRRR but from GEFS? Is there a particular reason that it's not using the HRRR data?

My question about mixed precipitations seems to have been missed so I'll ask again. On the chourly, minutely and currently blocks if there is more than one precipitation type which one is used?

**Comment by alexander0042** [comment]
Sorry for the confusion- where HRRR data is available, it is used, but runs into the same [processing hiccup](https://github.com/alexander0042/pirateweather/blob/4744667f178f4823519e8c66fd0ae865dcfa5c0f/scripts/hrrrh_combined-fargate.py#L196). To clarify, for precipitationIntensity:
- The currently and minutely data should come from HRRR when available, otherwise from GEFS
- The hourly and daily data always come from GEFS. 

The reason for the difference is because probabilities have to come from GEFS, so using that as the intensity source in the hourly and daily blocks ensures that these numbers are consistent (ex. avoids 0% probability with a 1 mm precipitation intensity).

For the second question (thanks for asking again, I had missed it). The approach to the type mirrors the intensity logic above, when HRRR data is available, then the most likely precipitation type is used, since the HRRR model spits one precipitation type (Snow, Ice Pellets, Freezing Rain, or Rain) out. When HRRR0 isn't available, the most common precipitation type from the ensemble forecast is used. So if 12 members show snow and 6 show freezing rain, and 1 shows ice pellets, the snow icon is used

**Comment by cloneofghosts** [comment]
So basically the models spit out which precipitation is most likely occurring and you use that to determining which `precipType` to use?

Maybe both of this could be documented somewhere or at least the `precipType` should be added to that blub on the documentation page.

**Comment by alexander0042** [comment]
Yup, exactly! If it's HRRR, it picks one and I pass that along, and outside of that I take the most common type from all the model runs, Definitely will update the docs for this one

**Comment by cloneofghosts** [comment]
Awesome thanks. Will close this issue once the update goes live where it uses hourly precipitation as a fallback if there's no realtime data.

**Comment by alexander0042** [comment]
That was trickier than it should have been, but working now! The new version is live and the docs (including some more detail for the precipitation intensity description) are updated.
