### ISSUE TITLE
PirateWeather HTTP Protocol Down

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#27]
@alexander0042 I'm getting a ERR_CONNECTION_REFUSED error when I try to query the API using both the dev and api urls. At first I thought it was the VPN so I tried disabling that and it didn't change anything.

I tried on a different device to see if it is just an issue on my computer but my phone is giving me the same error on WiFi and data. What's weird is that it doesn't seem to want to work in my browser but my Rainmeter card is working without issues. I also tried a different browser and it still doesn't work.

Is the API down or is it a weird issue on my end that's causing the issue?

EDIT: It works if I use Firefox but using a Chromium based browser doesn't seem to work. (Edge and Opera GX)

**Comment by alexander0042** [comment]
That's really weird. and an interesting sort of problem. Testing it on my end, this doesn't seem to be a browser specific as much as connection specific. Firefox (my daily browser), seems to automatically upgrade the connection to https://, while Chrome doesn't. This explains the difference, since http returns the "connection refused" while https doesn't. 

The question then becomes, why doesn't http work, since it really should. I'll have to dig into my cloudfront setup to parse this one out, but in the meantime https should get around this

**Comment by cloneofghosts** [comment]
Can confirm that using https instead of http fixes the issue.

**Comment by cloneofghosts** [comment]
I'm now getting ERR_EMPTY_RESPONSE visiting the api using http so it's at least connecting now.

Might be worth looking into creating a status page for the API. I've used UptimeRobot before so might be worthwhile to look into using them?

**Comment by cloneofghosts** [comment]
@alexander0042 Seems like whatever was causing the issue in my browser is fixed. I get taken to the https url now when visiting the api so that part is solved. The http url still seems to be broken and maybe a way to fix it would be to redirect from http to https if possible?

**Comment by alexander0042** [comment]
Agreed, since this seems to be resolved I'm going to close it for now. On a somewhat related note, I have an official status page put together, and just waiting a few days to make sure it's accurate: <https://stats.uptimerobot.com/DRKqBCok2N>. It should help addresses some of these issues, and will give me a rapid alert of any problems as they happen!

**Comment by cloneofghosts** [comment]
@alexander0042 Oh awesome! I noticed that the API is checked every 19m and the Dev API is every 20. I think you wanted both to be checked every 20m?
