### ISSUE TITLE
Facilitate Upload of Data from Personal Weather Stations

### ISSUE THREAD

**Issue by Tylast** [alexander0042/pirateweather#44]
It would be great if I could submit my local weather data to you from my Ambient Weather stations.  Below is a screenshot of the my weather stations' custom server input screen.

![IMG_1833](https://user-images.githubusercontent.com/8835107/230064641-4b303b38-d375-443f-9bae-4132858cab32.jpeg)

**Comment by cloneofghosts** [comment]
I'm not entirely sure what plans @alexander0042 has for station data but if I were to take a guess he would probably use data from this https://madis.ncep.noaa.gov data. It could be possible that allowing users to add their own station data is a long term plan but there hasn't been any mention of it.

**Comment by alexander0042** [comment]
Yup, that's the answer here. This would be a really great addition, but alas, is probably outside the scope of this project. The current roadmap is [here](http://pirateweather.net/en/latest/roadmap/), and at the moment the focus is on fixing the issues with the daily high/ low temperatures. This requires a pretty major rework of the ingest scripts (since they'll have to be aware of previous observations), so will be the focus for a bit
