### ISSUE TITLE
API Keys not being generated

### ISSUE THREAD

**Issue by int-rnd** [alexander0042/pirateweather#45]
I lost my API key and logged in. I clicked regenerate API key and all it did was delete the key. No new one was generated. I tried different browsers and different internet connections. The problem persists.

I then created a brand new account. I signed up for another subscription with a different email. Sadly the part of the page where the API key would be is completely missing. Here is what I see:

![image](https://user-images.githubusercontent.com/64692048/230194141-2a8343ee-e877-486d-b989-562cf498579e.png)

I wonder if https://pirate-weather.apiable.io/subscription/[redacted] is somehow not generating keys.

**Comment by alexander0042** [comment]
Hi,

Sorry for the issues here! Your theory is correct here- there seems to be some sort of issue with Apiable, and I've let them know to see if they can take a look at it. 

In the meantime, if you send an e-mail to api@alexanderrey.ca, I'm happy to manually generate a key for you to use.

Thanks,
Alexander

**Comment by FsFalcon** [comment]
I just ran into this issue as well - @alexander0042: I just sent you an email requesting a manual key generation.  Thanks for your work developing this, I'm really looking forward to checking it out!

**Comment by brycied00d** [comment]
Chiming-in with a similar experience. There just wasn't ANY mention of an API key. I couldn't find any mention anywhere, and the docs state simply "get your API key" so I figured I had to be missing something somewhere. I'm glad I found this issue, I know I'm not missing something obvious (or well, I am technically but it's not my fault).

I created a new subscription (same existing Apiable account) and that time, that subscription does show the API key field with a value in it. Nothing actually accepts that API key, so I'm stuck for the moment, but that's okay because I've run out of spare time to be playing with this.

Thanks for the project, it looks very interesting! And I really appreciate that it's drop-in compatible with the ex-DarkSky API.

**Comment by alexander0042** [comment]
Thank you to everyone here who commented, and sorry for the issues with this. The problem (came down to a database auth thing) has now been corrected (they were fantastic at solving this!), and keys should be showing up now. You can view it by clicking on "my subscriptions", then the exclamation mark on the far right of the screen. 

If anyone has any lingering issues, feel free to shoot me an e-mail, and again, sorry for all the issues today
