### ISSUE TITLE
API key generation auth loop

### ISSUE THREAD

**Issue by AskAlice** [alexander0042/pirateweather#52]
When i hit login, it redirects me to auth.apiable.com, then back to https://pirate-weather.apiable.io/ but with an iss query param contain a URI that returns an error if i decodeUriComponent and go to it manually
![image](https://user-images.githubusercontent.com/1855905/231361516-2d59a399-6a50-4873-8efc-d16efccfcd63.png)

I tried clearing the storage for pirate-weather.apiable.io and auth.apiable.io, but still nothing is different

**Comment by bendspoons** [comment]
Same here, cant login / cant select a plan :/

**Comment by alexander0042** [comment]
This is a long-standing issue that seems to crop of randomly for some people. It's a really tricky to debug since it seems to come and go, and is specific to the machine being used. For now, there are two approaches, neither of them great:
1. This seems to resolve itself after about a day, so worth trying again in a little bit.
2. e-mail me at api@alexanderrey.ca and I can create a key for you.

I've created a discussion #(60) for Apiable related issues, so I'm going to close this issue for now and try to centralize things over there. Definitely let me know how this ended up working out for you, and we can go from there!

**Comment by AskAlice** [comment]
I sent you an email more than a month ago and you still haven't gotten back to me, not sure why this issue is closed
