### ISSUE TITLE
Current API usage count missing in apiable

### ISSUE THREAD

**Issue by itsmikeferrari** [alexander0042/pirateweather#54]
In the old portal, I can see my current API calls usage. I can't find the same number in the new APIable system.
Does that exist and I'm overlooking it?

**Comment by tkafka** [comment]
+1 here. Also, is the app cut off when I use all of current month's limit, or is the computation continuous (eg. on day 15 of 30, you need to be under 1/2 of the limit)?
I am asking because PW stopped returning results for me halfway through the billing period, and at least according to my logs, I shouldn't be anywhere near the limit.

**Comment by alexander0042** [comment]
I'm going to consolidate this into the broader Apiable discussion (#60), so closing this for now. While I don't have a timeline for an improvement on their end, in the next couple weeks I'm going to be moving by back-end from AWS API Gateway to Kong, which will help with this in one small way. Kong returns usage as an API header, so once that's live (I'll send around an e-mail), at least there will be some way to check!
