### ISSUE TITLE
Subscription ends in 30 days

### ISSUE THREAD

**Issue by rss81** [alexander0042/pirateweather#57]
Hi, when you sign up for an api key it says subscription ends in 30 days.  Does the Subscription auto renew or do you have to signup again every 30 days?

**Comment by cloneofghosts** [comment]
The developer commented [on Reddit](https://old.reddit.com/r/selfhosted/comments/122m244/for_anyone_procrastinating_on_finding_another/jdryvd5/?context=3) that unless you cancel your subscription it should auto renew.

**Comment by alexander0042** [comment]
I did say that, and it remains correct! I'm working with Apiable to fix the wording here, since I don't want people worrying about it not auto-renewing or worse, not realizing it will auto renew. I think I need to make a page listing the Apiable specific changes that are in progress...

Since this is answered, I'm going to close it for now, but feel free to re-open or create a new issue if anything else comes up!
