### ISSUE TITLE
Legacy token issue post API Version 1.5

### ISSUE THREAD

**Issue by Privacywonk** [alexander0042/pirateweather#68]
Hi Alexander,

I noticed in the [change log](https://pirateweather.net/en/latest/changelog/) that a migration took place on May 26th. I just noticed today that my legacy API token is no longer working with Kong.

Making a call, e.g. https://api.pirateweather.net/forecast/[api_key]/39.4101,-74.3646 results in 

"Kong Error
You cannot consume this service."

Happy to send additional details on my key/account for tracing purposes if that would help.

Cheers & thank you so much for this project!

**Comment by Privacywonk** [comment]
I was able to sign up for a new API key to mitigate the outage on my end easily enough but given part of the messaging for the API says legacy keys will continue to work, happy to revert back to my old key and help test.

**Comment by alexander0042** [comment]
I’m so sorry about this issue, and thanks for filing it! Almost everything about the migration (which was a pretty significant reworking) went perfectly; however, there was one incredibly difficult to troubleshoot glitch with a small subset of the plans, and unfortunately, you got caught up in it. I believe I’ve corrected it now, so if you could let me know if things are back online for you, I would really appreciate it!

Thank you so much for subscribing, since this project really wouldn’t be possible without the support I’ve received from the community! Again, I’m really sorry for the glitch here, and appreciate your patience with fixing it.

**Comment by Privacywonk** [comment]
zero need for apologies, it's an evolving project. Bugs happen! I'll file em as I encouter so we can always make it better. 

As for sponsoring, I'm so glad I could. And a huge thank you for this project. 

When darksky announced their closure, I too started playing with NOAA data sets but I didn't have nearly enough time to dedicate to the task. Hell, groking netCDF data format took me a good long while.

**Comment by Privacywonk** [comment]
Just swapped back to my legacy token. All is well and working.
