### ISSUE TITLE
Precipitation Type Inconsistency

### ISSUE THREAD

**Issue by DaveL17** [alexander0042/pirateweather#78]
Data element `precipType` provides inconsistent and incorrect values.  For example, it's summer here and the value will sometimes be `snow`. Quite often it's `none` -- even when the probability of precipitation is non-zero. So I can get:

```python
f"Chance of {precipType}: {precipProbability}%"
```
- Chance of none: 10%
- Chance of snow: 10% (in summer)

with the exception of incongruous `rain` and `snow` values, I've been coercing the value to `precipitation` which works, but is suboptimal.

**Comment by alexander0042** [comment]
Thanks for opening this issue, and apologies for the slow reply here. 

There's two different aspects to this, both of which need to be addressed! The first is `none` showing up when there's no percentage, since that shouldn't happen, and the second is `snow` appearing when it shouldn't. I've got a hunch about what might be happening here. so let me dig into it and I'll report back.

**Comment by alexander0042** [comment]
Ok, got a solution! This error cropped up as a result of me trying to solve the long running "daily data from midnight to midnight vs 4 am to 4 am" problem, combined with how the GEFS model categorizes precipitation, since it can provide a value for precipitation but not a category. I'm working on improving the documentation on this now to make it clearer about how the type is selected in these cases, but in the meantime, I've fixed this bug by using the temperature to estimate a type. The `snow` response was just a straight up bug, so also fixed that! Changes are in version 1.5.3, which should be live shortly

**Comment by DaveL17** [comment]
Awesome. Thanks for taking care of this so quickly!

**Comment by alexander0042** [comment]
Great! I'm going to close this issue for now to keep things tidy, but feel free to either create a new issue or re-open if anything crops up
