### ISSUE TITLE
All icons are night icons

### ISSUE THREAD

**Issue by ion1** [alexander0042/pirateweather#79]
It seems all icons which can have a "day" or "night" suffix use "night" despite the sun being up at this location. The response to `https://api.pirateweather.net/forecast/.../61.4981,23.7604?exclude=minutely,hourly,daily,alerts` at 14:56 local time:

```json
{
	"latitude": 61.4981,
	"longitude": 23.7604,
	"timezone": "Europe/Helsinki",
	"offset": 3.0,
	"elevation": 354,
	"currently": {
		"time": 1687348560,
		"summary": "Clear",
		"icon": "clear-night",
		"nearestStormDistance": 0,
		"nearestStormBearing": 0,
		"precipIntensity": 0.0,
		"precipProbability": 0.0,
		"precipIntensityError": 0.0,
		"precipType": "none",
		"temperature": 84.47,
		"apparentTemperature": 84.65,
		"dewPoint": 45.01,
		"humidity": 0.25,
		"pressure": 999.85,
		"windSpeed": 8.124,
		"windGust": 11.59,
		"windBearing": 247.73,
		"cloudCover": 0,
		"uvIndex": 6.0,
		"visibility": 10.0,
		"ozone": 313.92
	},
	"flags": {
		"sources": [
			"ETOPO1",
			"gfs",
			"gefs"
		],
		"sourceTimes": {
			"gfs": "2023-06-21 06:00:00",
			"gefs": "2023-06-21 00:00:00"
		},
		"nearest-station": 0,
		"units": "us",
		"version": "V1.5.2"
	}
}
```

**Comment by alexander0042** [comment]
Thanks for bringing this up- I hadn't noticed it before, but I can verify it's still an issue for this region. The icons are working correctly in North America; however, I can also see that the sunrise/ sunset times are not working, so I think that's the root problem here. I'll dig into this and get back with a fix ASAP!

**Comment by alexander0042** [comment]
Ok, got it, another literal edge (of the map) case! The issue here was with the error handling when there [isn't a sunset](https://www.timeanddate.com/sun/finland/tampere), since the algorithm defaulted to assuming it was always night, instead of working out if it should be always day or night. I fixed this by checking the month and location, and then picking "always day" or "always night" from there. The API will then return a sunrise of 1 second after midnight and 1 second before midnight in the case of "always day", or a sunrise of 2 seconds before midnight and a sunset 1 second before midnight for "always night". I'll make version 1.5.3 with this change live shortly, and update the changelog/ docs with this corrected approach.

Thanks again for pointing this out, and let me know if you run into any other issues.
