### ISSUE TITLE
1.1.7 Documentation

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#8]
Instead of adding to issue #30 in the HA repository I'd create a separate topic about this.

It's been about 2 weeks since the 1.1.7 update on the dev API and it seems like the update hasn't been pushed live yet. I checked this morning and the main API is still on 1.1.6. Documentation will need to be updated here as well so just a reminder to do that at some point as well.

**Comment by alexander0042** [comment]
Thanks for the reminder! It's been a crazy few weeks (our first child was born in early August), so other than making sure that everything stayed up I haven't had time to work on this. Things are calming down now though, so since everything has been working on the .dev backend (this was an long beta test!), I'll put it live now 😊 and update the log

**Comment by cloneofghosts** [comment]
I figured you've been busier since you haven't been as responsive to issues as you were earlier. Anyways congrats on the child!

Do you want this issue left open as a reminder to do documentation or do you have it on a list somewhere and this issue can be closed?

**Comment by cloneofghosts** [comment]
I see that there's been a 1.1.8 update on dev that hasn't been released for about a month or so. I think because you've been so busy you forgot to launch it as well.

The changelog is still not displaying correctly and it's hard to read.

**Comment by alexander0042** [comment]
That's 100% what was wrong here! 1.1.8 is now live ☀️ It's an important one to update the docs for, since it's a "data change" instead of just a processing change. To try to improve results near shorelines (Sydney in particular), I changed the interpolation weighting function for the GFS/ GEFS data sources from inverse distance (1/distance) to inverse distance squared (1/distance^2). This has the effect of weighting the nearest cell more, especially when the requested point is close to the middle of a cell. 

Docs have also been updated to fix the formatting issue. It was only one missing line break that broke everything, but such is markdown.
